import type { Metadata } from "next"
import { TooltipProvider } from "@/components/ui/tooltip"
import { AuthProvider } from "@/components/contexts/auth"
import { CartProvider } from "@/components/contexts/cart"
import { getUser } from "@/lib/auth"
import { Toaster } from "sonner"
import Features from "@/components/home/Features"
import Footer from "@/components/home/Footer"
import Navbar from "@/components/home/Navbar"
import "./styles.css"
import { fetchCart } from "@/actions/cart"

export const metadata: Metadata = {
    title: "itsMU1X @",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.png",
    },
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const cart = await fetchCart()
    console.log(cart)
    const user = await getUser()

    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <CartProvider initialCart={cart}>
                    <AuthProvider initialUser={user}>
                        <TooltipProvider delayDuration={350}>
                            <Navbar />

                            {children}

                            <div className="container divide-bottom">
                                <Features />
                            </div>

                            <Footer />
                        </TooltipProvider>
                    </AuthProvider>
                </CartProvider>

                <Toaster
                    containerAriaLabel="Toaster"
                    duration={3250}
                    closeButton
                    position="bottom-right"
                    theme="light"
                    richColors
                />
            </body>
        </html>
    )
}
